### ISSUE TITLE
Gurobi solver and larger instances

### ISSUE THREAD

**Issue by aabbas90** [fabiofurini/LocationCovering#1]
Hi, Thanks for the repository. 

1. I am testing the Gurobi solver on the provided MCLP instances and getting very fast performance. Mainly I see that presolving is removing a lot of variables and constraints. Possibly my parser is incorrect? As an example I am getting following results:

| Instance  |  budget | radius  | objective  | time (sec.)  |
|---|---|---|---|---|
|  GRID_MCLP_n100_m100000_d1_100_f1_1_s1.dat |  10 | 5.5  |  4.43e+06 | 5 |
|  GRID_MCLP_n100_m100000_d1_100_f1_1_s2.dat |  10 | 5.5  |  4.37e+06 | 5.5 |

Could you please verify if the objective values match with your results? For completeness the python script is [available](https://gist.github.com/aabbas90/0ddaa58b7ad0cfcd40670566146d9c7c).

2. Would it be possible to provide the 'massive MCLP data sets' used in the paper?

Thanks,
Ahmed

**Comment by fabiofurini** [comment]
Hi, thanks for your comments. It is indeed possible that gurobi solves the instances faster than cplex by preprocessing most of the variables and constraints. To check the value it is sufficient to run the code on the desired instance and it will print the objective function value. For the larger instances I've updaload an instance generator, so you can generate instances of the size you like.
